//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdApp_Pushkina_Tciguleeva_422
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int ad_id { get; set; }
        public int user_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime post_date { get; set; }
        public int city_id { get; set; }
        public int category_id { get; set; }
        public int type_id { get; set; }
        public int status_id { get; set; }
        public int price { get; set; }
        public Nullable<int> profit { get; set; }
        public string photo_path { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual AdTypes AdTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
